version: "3.5"

services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    command: "sh /etc/nginx/start-nginx.sh"
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 8000:8000
    volumes:
      - ./nginx/logs/nginx/:/var/log/nginx/
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      # - ./backend/static:/var/www/static/
    depends_on:
      - django

  next.js:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend/
    command: yarn dev

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "sh /backend/start-django.sh"
    env_file: ./backend/.django_env
    environment:
      DATABASE_HOST: db
    expose:
      - "8001"
    volumes:
      - ./backend:/backend/
    depends_on:
      - db

  db:
    image: postgres:latest
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./db/.postgres_env
    command: 'postgres -c config_file="/etc/postgresql.conf"'
volumes:
  dbdata:
