# Generated by Django 4.1.5 on 2023-02-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookitem',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'g'), (1, 'ml'), (2, 'cc'), (3, '大さじ'), (4, '小さじ'), (5, '適量'), (6, '個')], null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='cookitem',
            name='cookbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookitem', to='app.cookbook'),
        ),
    ]
