# Generated by Django 4.1.5 on 2023-02-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cookitem_unit_alter_cookitem_cookbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookitem',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'g'), (1, 'ml'), (2, 'cc'), (3, '大さじ'), (4, '小さじ'), (5, '適量'), (6, '個')], null=True, verbose_name='単位'),
        ),
    ]
