# Generated by Django 4.1.5 on 2023-02-18 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cookitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookitem',
            name='cookbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbook', to='app.cookbook'),
        ),
    ]
